build: 
	g++ -Wall -c -o calculator.o calculator.cpp; g++ -o calculator calculator.o
	g++ -Wall -c -o functions.o functions.cpp; g++ -o functions functions.o
	g++ -Wall -c -o dayofmonth.o dayofmonth.cpp; g++ -o dayofmonth dayofmonth.o
	g++ -Wall -c -o funny.o funny.cpp; g++ -o funny funny.o
	g++ -Wall -c -o acumulator.o acumulator.cpp; g++ -o acumulator acumulator.o
	g++ -Wall -c -o exvector.o exvector.cpp; g++ -o exvector exvector.o
	g++ -Wall -c -o amo.o amo.cpp; g++ -o amo amo.o
	g++ -Wall -c -o multiplesofsix.o multiplesofsix.cpp; g++ -o multiplesofsix multiplesofsix.o
	g++ -Wall -c -o rand.o rand.cpp; g++ -o rand rand.o
	g++ -Wall -c -o sqrtsinlog.o sqrtsinlog.cpp; g++ -o sqrtsinlog sqrtsinlog.o
	g++ -Wall -c -o swithcase.o swithcase.cpp; g++ -o swithcase swithcase.o
	g++ -Wall -c -o while.o while.cpp; g++ -o while while.o
	g++ -Wall -c -o ifcomp.o ifcomp.cpp; g++ -o ifcomp ifcomp.o
	g++ -Wall -c -o vogal.o vogal.cpp; g++ -o vogal vogal.o
	g++ -Wall -c -o library.o library.cpp; g++ -o library library.o
	g++ -Wall -c -o comparing.o comparing.cpp; g++ -o comparing comparing.o
	g++ -Wall -c -o concatenate.o concatenate.cpp; g++ -o concatenate concatenate.o 
	g++ -Wall -c -o characnull.o characnull.cpp; g++ -o characnull characnull.o
	g++ -Wall -c -o charsimple.o charsimple.cpp; g++ -o charsimple charsimple.o
	g++ -Wall -c -o colors.o colors.cpp; g++ -o colors colors.o
	g++ -Wall -c -o sum.o sum.cpp; g++ -o sum sum.o
	g++ -Wall -c -o opt.o opt.cpp; g++ -o opt opt.o
	g++ -Wall -c -o sizestring.o sizestring.cpp; g++ -o sizestring sizestring.o
	g++ -Wall -c -o caracnull.o caracnull.cpp; g++ -o caracnull caracnull.o
	g++ -Wall -c -o days.o days.cpp; g++ -o days days.o
	g++ -Wall -c -o caracnum.o caracnum.cpp; g++ -o caracnum caracnum.o
	g++ -Wall -c -o name.o name.cpp; g++ -o name name.o
	g++ -Wall -c -o ponteiro.o ponteiro.cpp; g++ -o ponteiro ponteiro.o
	g++ -Wall -c -o ponteiro2.o ponteiro2.cpp; g++ -o ponteiro2 ponteiro2.o
	g++ -Wall -c -o hello.o hello.cpp; g++ -o hello hello.o
	g++ -Wall -c -o funcmore.o funcmore.cpp; g++ -o funcmore funcmore.o
	g++ -Wall -c -o ponteiro3.o ponteiro3.cpp; g++ -o ponteiro3 ponteiro3.o
	g++ -Wall -c -o ponteiro4.o ponteiro4.cpp; g++ -o ponteiro4 ponteiro4.o
	g++ -Wall -c -o parray.o parray.cpp; g++ -o parray parray.o
	g++ -Wall -c -o ponteiro5.o ponteiro5.cpp; g++ -o ponteiro5 ponteiro5.o
	g++ -Wall -c -o ponteiro6.o ponteiro6.cpp; g++ -o ponteiro6 ponteiro6.o
	g++ -Wall -c -o ponteiro7.o ponteiro7.cpp; g++ -o ponteiro7 ponteiro7.o
	g++ -Wall -c -o ponteiro8.o ponteiro8.cpp; g++ -o ponteiro8 ponteiro8.o
	g++ -Wall -c -o funcstrupr.o funcstrupr.cpp; g++ -o funcstrupr funcstrupr.o
	g++ -Wall -c -o dc.o dc.cpp; g++ -o dc dc.o
	g++ -Wall -c -o varglob.o varglob.cpp; g++ -o varglob varglob.o
	g++ -Wall -c -o modulo.o modulo.cpp; g++ -o modulo modulo.o
	g++ -Wall -c -o operadores.o operadores.cpp; g++ -o operadores operadores.o
	g++ -Wall -c -o decision.o decision.cpp; g++ -o decision decision.o
	g++ -Wall -c -o regres.o regres.cpp; g++ -o regres regres.o
	g++ -Wall -c -o wtf.o wtf.cpp; g++ -o wtf wtf.o
	g++ -Wall -c -o moreone.o moreone.cpp; g++ -o moreone moreone.o
	g++ -Wall -c -o para.o para.cpp; g++ -o para para.o
	g++ -Wall -c -o para2.o para2.cpp; g++ -o para2 para2.o
	g++ -Wall -c -o para3.o para3.cpp; g++ -o para3 para3.o
	g++ -Wall -c -o para4.o para4.cpp; g++ -o para4 para4.o
	g++ -Wall -c -o dw.o dw.cpp; g++ -o dw dw.o
	g++ -Wall -c -o simplestdlib.o simplestdlib.cpp; g++ -o simplestdlib simplestdlib.o
	g++ -Wall -c -o newhile.o newhile.cpp; g++ -o newhile newhile.o
	g++ -Wall -c -o loopnested.o loopnested.cpp; g++ -o loopnested loopnested.o
	g++ -Wall -c -o loopagain.o loopagain.cpp; g++ -o loopagain loopagain.o
	g++ -Wall -c -o doenquanto.o doenquanto.cpp; g++ -o doenquanto doenquanto.o
	g++ -Wall -c -o func1.o func1.cpp; g++ -o func1 func1.o
	g++ -Wall -c -o func2.o func2.cpp; g++ -o func2 func2.o
	g++ -Wall -c -o prototipo.o prototipo.cpp; g++ -o prototipo prototipo.o
	g++ -Wall -c -o func3.o func3.cpp; g++ -o func3 func3.o
	g++ -Wall -c -o const1.o const1.cpp; g++ -o const1 const1.o
	g++ -Wall -c -o charvector.o charvector.cpp; g++ -o charvector charvector.o
	g++ -Wall -c -o charfunc.o charfunc.cpp; g++ -o charfunc charfunc.o
	g++ -Wall -c -o charfunc1.o charfunc1.cpp; g++ -o charfunc1 charfunc1.o
	g++ -Wall -c -o charfunc2.o charfunc2.cpp; g++ -o charfunc2 charfunc2.o
	g++ -Wall -c -o ponteiro9.o ponteiro9.cpp; g++ -o ponteiro9 ponteiro9.o
	g++ -Wall -c -o ponteiro10.o ponteiro10.cpp; g++ -o ponteiro10 ponteiro10.o
	g++ -Wall -c -o rand2.o rand2.cpp; g++ -o rand2 rand2.o
	g++ -Wall -c -o poref.o poref.cpp; g++ -o poref poref.o
	g++ -Wall -c -o matrizes.o matrizes.cpp; g++ -o matrizes matrizes.o
	g++ -Wall -c -o memory.o memory.cpp; g++ -o memory memory.o
	g++ -Wall -c -o memory2.o memory2.cpp; g++ -o memory2 memory2.o
	g++ -Wall -c -o pointer.o pointer.cpp; g++ -o pointer pointer.o
	g++ -Wall -c -o manipuladores.o manipuladores.cpp; g++ -o manipuladores manipuladores.o
	g++ -Wall -c -o manipuladores1.o manipuladores1.cpp; g++ -o manipuladores manipuladores.o
	g++ -Wall -c -o manipuladores2.o manipuladores2.cpp; g++ -o manipuladores2 manipuladores2.o
	g++ -Wall -c -o structs.o structs.cpp; g++ -o structs structs.o
	g++ -Wall -c -o structs1.o structs1.cpp; g++ -o structs1 structs1.o
	g++ -Wall -c -o structs2.o structs2.cpp; g++ -o structs2 structs2.o
.PHONY: